# Generated by Django 5.2.11 on 2026-05-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='ارزش موجودی (تومان)'),
        ),
    ]
