# Generated by Django 5.2.11 on 2026-05-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_product_is_featured_product_inventory_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='نمایش در دسترسی سریع'),
        ),
    ]
