# Generated by Django 5.2.11 on 2026-05-17 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('calculation_type', models.CharField(choices=[('fixed_per_unit', 'مبلغ ثابت به ازای هر واحد'), ('percentage', 'درصدی')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applies_on', models.CharField(choices=[('base_price', 'قیمت پایه (قبل از مالیات)'), ('cumulative', 'جمع قیمت پایه + مالیات\u200cهای قبلی')], default='base_price', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TaxLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_lines', to='sales.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('tax_rules', models.ManyToManyField(blank=True, to='taxation.taxrule')),
            ],
        ),
    ]
