# Generated by Django 5.2.11 on 2026-05-23 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_category_options_alter_product_options_and_more'),
        ('sales', '0005_alter_customer_options_alter_order_options_and_more'),
        ('taxation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttaxprofile',
            options={'verbose_name': 'پروفایل مالیاتی', 'verbose_name_plural': 'پروفایل\u200cهای مالیاتی'},
        ),
        migrations.AlterModelOptions(
            name='taxline',
            options={'verbose_name': 'خط مالیاتی', 'verbose_name_plural': 'خطوط مالیاتی'},
        ),
        migrations.AlterModelOptions(
            name='taxrule',
            options={'ordering': ['order'], 'verbose_name': 'قانون مالیاتی', 'verbose_name_plural': 'قوانین مالیاتی'},
        ),
        migrations.AlterField(
            model_name='producttaxprofile',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='producttaxprofile',
            name='tax_rules',
            field=models.ManyToManyField(blank=True, to='taxation.taxrule', verbose_name='قوانین مالیاتی'),
        ),
        migrations.AlterField(
            model_name='taxline',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ (تومان)'),
        ),
        migrations.AlterField(
            model_name='taxline',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_lines', to='sales.orderitem', verbose_name='آیتم فروش'),
        ),
        migrations.AlterField(
            model_name='taxline',
            name='rule_name',
            field=models.CharField(max_length=100, verbose_name='نام قانون'),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='applies_on',
            field=models.CharField(choices=[('base_price', 'قیمت پایه (قبل از مالیات)'), ('cumulative', 'جمع قیمت پایه + مالیات\u200cهای قبلی')], default='base_price', max_length=20, verbose_name='مبنای محاسبه'),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='calculation_type',
            field=models.CharField(choices=[('fixed_per_unit', 'مبلغ ثابت به ازای هر واحد'), ('percentage', 'درصدی')], max_length=20, verbose_name='نوع محاسبه'),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب اجرا'),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار'),
        ),
    ]
