# Generated by Django 5.2.11 on 2026-05-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_customer_order_discount_amount_order_discount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='بهای تمام\u200cشده واحد (تومان)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_type',
            field=models.CharField(default='none', max_length=10),
        ),
    ]
