# Generated by Django 5.2.11 on 2026-05-23 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_orderitem_purchase_cost_alter_order_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_return',
            field=models.BooleanField(default=False, verbose_name='فاکتور برگشتی'),
        ),
        migrations.AddField(
            model_name='order',
            name='original_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_orders', to='sales.order', verbose_name='فاکتور اصلی'),
        ),
    ]
