# Generated by Django 5.2.11 on 2026-05-23 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_category_options_alter_product_options_and_more'),
        ('sales', '0004_order_is_return_order_original_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'مشتری', 'verbose_name_plural': 'مشتریان'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'اقلام فروش', 'verbose_name_plural': 'اقلام فروش'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت\u200cها'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='اعتبار (تومان)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مشتری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='تلفن مشتری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ تخفیف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_type',
            field=models.CharField(default='none', max_length=10, verbose_name='نوع تخفیف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_value',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مقدار تخفیف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='grand_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قابل پرداخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='held_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ نگهداری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_held',
            field=models.BooleanField(default=False, verbose_name='نگهداری شده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='جمع کل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_tax',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='جمع مالیات'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='کالا'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مالیات (تومان)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت فروش واحد (تومان)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ (تومان)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'نقد'), ('card', 'کارت'), ('credit', 'اعتباری')], max_length=10, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان پرداخت'),
        ),
    ]
