# Generated by Django 5.2.11 on 2026-06-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_customer_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='برگشت خورده'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='returned_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='تعداد برگشتی'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='تعداد'),
        ),
    ]
